version: '2'

services:
  nginx1:
    image: nginx:1.15.9-alpine
    container_name: nginx1
    hostname: nginx1
    volumes:
    - /home/w/tool/nginx/html:/usr/share/nginx/html
    - /home/w/tool/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/w/tool/nginx/www:/www
    - /home/w/tool/nginx/logs:/wwwlogs
    ports:
    - "8041:80"

  nginx2:
    image: nginx:1.15.9-alpine
    container_name: nginx2
    hostname: nginx2
    volumes:
    - /home/w/tool/nginx/html:/usr/share/nginx/html
    - /home/w/tool/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/w/tool/nginx/www:/www
    - /home/w/tool/nginx/logs:/wwwlogs
    ports:
    - "8042:80"