version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wp_w
    hostname: wp_w
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: newcapec

  mysql:
    image: mysql:5.7
    restart: always
    container_name: wp_db
    hostname: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: newcapec