---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ansible_hostname
    debug: msg="hello {{ ansible_hostname.upper() }}"
  - debug: msg="hello {{ ansible_os_family.upper() }}"
  - debug: msg="ansible_all_ipv4_addresses {{ ansible_all_ipv4_addresses }}"
  - debug: msg="ansible_default_ipv4 {{ ansible_default_ipv4 }}"
  - debug: msg="ansible_enp0s8.ipv4 {{ ansible_enp0s8.ipv4.address,ansible_enp0s8.ipv4.broadcast,ansible_enp0s8.ipv4.netmask,ansible_enp0s8.ipv4.network }}"
  - debug: msg="ansible_distribution {{ ansible_distribution }}"
  - debug: msg="ansible_lsb {{ ansible_lsb }}"
  - debug: msg="ansible_memtotal_mb {{ ansible_memtotal_mb }}"
  - debug: msg="ansible_processor {{ ansible_processor }}"
  - debug: msg="ansible_python_version {{ ansible_python_version }}"
  - debug: msg="ansible_selinux {{ ansible_selinux }}"
  - debug: msg="facter_fqdn {{ facter_fqdn }}"
  - debug: msg="facter_os {{ facter_os }}"
  - debug: msg="facter_partitions {{ facter_partitions }}"
  - debug: msg="facter_system_uptime {{ facter_system_uptime }}"

  # Example that prints the loopback address and gateway for each host
  - debug:
     msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
  - debug:
     msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
    when: ansible_default_ipv4.gateway is defined

  - shell: /usr/bin/uptime
    register: result
  - debug:
     var: result
     #verbosity: 2

  - shell: /usr/bin/lsb_release -a
    register: result2
  - debug:
     var: result2
     #verbosity: 2

  - name: Display all variables/facts known for a host
    debug:
     var: hostvars[inventory_hostname]
     #verbosity: 4
