---
# - config:
#     - testset: "Tests using test app"

# - test: # create entity
#     - name: "Basic get"
#     - url: "/api/person/"
requirements:
  - "wget"
  - "tree"
  - "vim"
  - "net-tools"
  - "createrepo"
  - "zip"
  - "unzip"
  - "ntp"
  - "httpd"
  - "ansible"
  - "docker-ce-18.06.1.ce"
  - ""
  - ""
  - ""
