- name: oracle database 11g (11.2.0.4)
  hosts: 172.17.8.241

  roles:
    #- role: nfs
    #  nfs_mode: client
    #  nfs_client_imports:
    #    -
    #      local: /srv/files
    #      remote: /installers/oracle/db/11.2/database/11.2.0.4
    #      server_host: 10.0.0.1
    - role: sysco-middleware.oracle-database
      # installation variables
      oracle_database_version: 11g # supported versions: [11g]
      oracle_database_release: 11.2.0.4 # supported releases: [11.2.0.4]
      oracle_database_edition: EE # supported editions: [SE,EE]
      #oracle_database_installer_directory: /oracle/oracle11.2.0.4/database
      # installers
      oracle_database_installer: /oracle/oracle11.2.0.4/database/runInstaller
    - role: sysco-middleware.oracle-database-instance
      oracle_database_version: 11g # supported versions: [11g]
      # instance variables
      oracle_database_sid: TESTDB
      oracle_database_global_name: TESTDB
      oracle_database_template_name: General_Purpose.dbc
      oracle_database_admin_password: welcome1
      oracle_database_auto_memory_mgnt: TRUE
      oracle_database_memory_percentage: 80
      oracle_database_memory_total: 1024
      oracle_database_type: MULTIPURPOSE
      # listener variables
      oracle_database_listener_name: LISTENER
      oracle_database_listener_port: 1521
      # avoid error in docker related with https://community.oracle.com/thread/2401396
      oracle_database_init_params: JAVA_JIT_ENABLED=FALSE