---
- hosts: test
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: deliver authorized_keys
    authorized_key:
      user: root
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
      exclusive: yes
