---
- hosts: test 
  remote_user: root

  tasks:
    - name: create new file
      file: name=/home state=touch
    - name: create new user
      user: name=test2 system=yes shell=/sbin/nologin
    - name: install package
      yum: name=httpd
    - name: copy html
      copy: scr=$PWD/index.html dest=/var/www/html/
    - name: start service
      service: name=httpd state=started enabled=yes
